### ISSUE TITLE
active project

### ISSUE THREAD

**Issue by pergolafabio** [NoUseFreak/niko-home-control#7]
is this still an active project? seems the platform in Home assistant is still not working?

thnx for the feedback

**Comment by NoUseFreak** [comment]
It will only work when you have NHC1, v2 has a different api and this project is not compatible with the newer version.

**Comment by pergolafabio** [comment]
i believe we tested V1 

this was issue : 

https://github.com/home-assistant/home-assistant/issues/19283

**Comment by pergolafabio** [comment]
confirmed, user was testing Niko V1

any update please? how can we test?

**Comment by NoUseFreak** [comment]
@pergolafabio I have a new PR out to HA upgrading to the latest version of this project. This should resolve this.

**Comment by pergolafabio** [comment]
ah, thnx for the feedback, much appreciated

**Comment by pergolafabio** [comment]
ok, closed this one : https://github.com/home-assistant/home-assistant/issues/19283

**Comment by pergolafabio** [comment]
Hey, same issue is still present after updating to 92.0?
https://github.com/home-assistant/home-assistant/issues/19283
